---
driver:
  name: dokken
  privileged: true
  chef_version: 12.13.37

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: debian
  driver_config:
    image: debian:jessie-slim
    intermediate_instructions:
      - RUN /usr/bin/apt-get update && /usr/bin/apt-get install lsb-release net-tools --yes --no-install-recommends

verifier:
  name: inspec
  root_path: '/opt/verifier'
  sudo: false

suites:
  - name: create
    run_list:
      - recipe[sumologic-syslog-test::rsyslog-create]
  - name: remove
    run_list:
      - recipe[sumologic-syslog-test::rsyslog-remove]
